export const RAW_CREATE = 'RAW_CREATE';
export const RAW_FETCH = 'RAW_FETCH';
export const RAW_FETCH_ALL = 'RAW_FETCH_ALL';
export const RAW_UPDATE = 'RAW_UPDATE';
export const RAW_DELETE = 'RAW_DELETE';

export const RECIPE_CREATE = 'RECIPE_CREATE';
export const RECIPE_FETCH = 'RECIPE_FETCH';
export const RECIPE_FETCH_ALL = 'RECIPE_FETCH_ALL';
export const RECIPE_UPDATE = 'RECIPE_UPDATE';
export const RECIPE_DELETE = 'RECIPE_DELETE';

// export const OTHER_COSTS_CREATE = 'OTHER_COSTS_CREATE';
export const OTHER_COSTS_FETCH = 'OTHER_COSTS_FETCH';
// export const OTHER_COSTS_FETCH_ALL = 'OTHER_COSTS_FETCH_ALL';
export const OTHER_COSTS_UPDATE = 'OTHER_COSTS_UPDATE';
// export const OTHER_COSTS_DELETE = 'OTHER_COSTS_DELETE';

export const PRODUCTS_CREATE = 'PRODUCTS_CREATE';
export const PRODUCTS_FETCH = 'PRODUCTS_FETCH';
export const PRODUCTS_FETCH_ALL = 'PRODUCTS_FETCH_ALL';
export const PRODUCTS_UPDATE = 'PRODUCTS_UPDATE';
export const PRODUCTS_DELETE = 'PRODUCTS_DELETE';
